### ISSUE TITLE
How to add prefixes

### ISSUE THREAD

**Issue by SteinerPascal** [tpluscode/sparql-builder#81]
In the README you have the following example:
```
import { variable } from '@rdfjs/data-model'
import namespace from '@rdfjs/namespace'
import { prefixes } from '@zazuko/rdf-vocabularies'
import { SELECT } from '@tpluscode/sparql-builder'

const ex = namespace('http://example.com/')
const foaf = namespace(prefixes.foaf)

/*
    PREFIX foaf: <http://xmlns.com/foaf/0.1/>

    SELECT ?person ?name
    FROM <http://example.com/People>
    WHERE 
    {
      ?person a foaf:Person ;
              foaf:name ?name .
    }
*/
const person = variable('person')
const query = 
  SELECT`${person} ?name`
  .FROM(ex.People)
  .WHERE`
    ${person} a ${foaf.Person} ; 
              ${foaf.name} ?name .
  `.build()
```
Where does the prefix `PREFIX foaf: <http://xmlns.com/foaf/0.1/>` within the built SPARQL query comes from? Is it possible to give a list of prefixes as parameters so i can make use of more readable queries using prefixes?

Edit: Just saw this one: https://github.com/tpluscode/sparql-builder/blob/c4f176118088fab70e1c5eb414ae55c30ca6bfcd/docs/README.md
So then i guess it only uses the common vocabulary. Then i would have a prefix list as constructor parameter (or parameter for the `build()` method) as a feature request if you are open for it =)

**Comment by tpluscode** [comment]
Hello. Thank you for asking and a good suggestion

Internally, another package [@tpluscode/rdf-string](https://npm.im/@tpluscode/rdf-string) is used to process the string templates and replace named node with prefixed names where the namespace is known.

As you found, effectively the list of known prefixes is the same as that of Zazuko's prefix server at https://prefix.zazuko.com/

Yes, I think I would add a `prefixes` option to the `build` function so that prefixes can be provided for a query. That will actually go to `@tpluscode/rdf-string`, which as I said assembles the final SPARQL

In the meantime, you can actually add prefixes globally. Check the very bottom of [@zazuko/rdf-vocabularies](https://github.com/zazuko/rdf-vocabularies#project-specific-prefixes). On second thought, that could also be exposed directly in rdf-string so that one does not need to import many packages

**Comment by SteinerPascal** [comment]
Cool then I'm going to use the project prefixes as a work-around. Thanks for the quick reply and the open source library!

**Comment by tpluscode** [comment]
@SteinerPascal please try version `0.3.26`

**Comment by SteinerPascal** [comment]
I'll try it thanks a lot!
